from session.circuit import Circuit, BlocExercice,MODE_CHRONO,MODE_MAINTIEN,MODE_REPETITIONS,MODE_AMRAP

from mouvements.exercices import (
    curl_biceps_droit,
    curl_biceps_gauche,
    elevation_laterale,
    pompe,
    extension_triceps_au_dessus_de_la_tete,
    developpe_couche_sol,
    developpe_epaule,
    crunches,
    planche,
    squat,
    fente_droite,
    fente_gauche,
    souleve_roumain,
    planche_laterale_droite,
    planche_laterale_gauche
)

Test_exercice = Circuit([
    BlocExercice(
        exercice=planche_laterale_droite,
        poids=0,
        mode=MODE_MAINTIEN,
        nombre_series=1,
        repetitions_par_serie=0,
        duree=300,
        repos_entre_series=30,
        repos_apres=10
    )
])

seance_bras = Circuit([
    BlocExercice(
        exercice=curl_biceps_droit,
        poids=8,
        mode=MODE_REPETITIONS,
        nombre_series=2,
        repetitions_par_serie=5,
        duree=0,
        repos_entre_series=5,
        repos_apres=10
    ),
    BlocExercice(
        exercice=curl_biceps_gauche,
        poids=8,
        mode=MODE_REPETITIONS,
        nombre_series=1,
        repetitions_par_serie=5,
        duree=0,
        repos_entre_series=30,
        repos_apres=0
    )
])

seance_test = Circuit([
    BlocExercice(
        exercice=curl_biceps_droit,
        poids=8,
        mode=MODE_REPETITIONS,
        nombre_series=2,
        repetitions_par_serie=5,
        duree=0,
        repos_entre_series=15,
        repos_apres=30,
    ),
    BlocExercice(
        exercice=planche,
        poids=0,
        mode=MODE_MAINTIEN,
        nombre_series=2,
        repetitions_par_serie=None,
        duree=10,
        repos_entre_series=15,
        repos_apres=30,
    ),
    BlocExercice(
        exercice=curl_biceps_gauche,
        poids=8,
        mode=MODE_AMRAP,
        nombre_series=2,
        repetitions_par_serie=0,
        duree=10,
        repos_entre_series=15,
        repos_apres=30,
    ),
    BlocExercice(
        exercice=elevation_laterale,
        poids=5,
        mode=MODE_REPETITIONS,
        nombre_series=1,
        repetitions_par_serie=5,
        duree=0,
        repos_entre_series=5,
        repos_apres=30,
    ),
    BlocExercice(
        exercice=pompe,
        poids=0,
        mode=MODE_REPETITIONS,
        nombre_series=1,
        repetitions_par_serie=5,
        duree=0,
        repos_entre_series=5,
        repos_apres=30,
    ),
    BlocExercice(
        exercice=extension_triceps_au_dessus_de_la_tete,
        poids=14,
        mode=MODE_REPETITIONS,
        nombre_series=1,
        repetitions_par_serie=5,
        duree=0,
        repos_entre_series=5,
        repos_apres=30,
    ),
    BlocExercice(
        exercice=developpe_couche_sol,
        poids=10,
        mode=MODE_REPETITIONS,
        nombre_series=1,
        repetitions_par_serie=5,
        duree=0,
        repos_entre_series=5,
        repos_apres=0
    )
])

seance_Upper_Push = Circuit([
    BlocExercice(
        exercice=developpe_couche_sol,
        poids=10,
        mode=MODE_REPETITIONS,
        nombre_series=4,
        repetitions_par_serie=12,
        duree=0,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=pompe,
        poids=0,
        mode=MODE_REPETITIONS,
        nombre_series=4,
        repetitions_par_serie=10,
        duree=0,
        repos_entre_series=60,
        repos_apres=90
    ),
    BlocExercice(
        exercice=developpe_epaule,
        poids=8,
        mode=MODE_REPETITIONS,
        nombre_series=3,
        repetitions_par_serie=12,
        duree=0,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=elevation_laterale,
        poids=5,
        mode=MODE_REPETITIONS,
        nombre_series=3,
        repetitions_par_serie=11,
        duree=0,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=extension_triceps_au_dessus_de_la_tete,
        poids=14,
        mode=MODE_REPETITIONS,
        nombre_series=3,
        repetitions_par_serie=10,
        duree=0,
        repos_entre_series=60,
        repos_apres=0
    ),
])

seance_jambes_abdos = Circuit([
    BlocExercice(
        exercice=squat,
        poids=10,
        mode=MODE_REPETITIONS,
        nombre_series=4,
        repetitions_par_serie=10,
        duree=0,
        repos_entre_series=50,
        repos_apres=90
    ),
    BlocExercice(
        exercice=fente_droite,
        poids=10,
        mode=MODE_REPETITIONS,
        nombre_series=4,
        repetitions_par_serie=10,
        duree=0,
        repos_entre_series=45,
        repos_apres=90
    ),    
    BlocExercice(
        exercice=fente_gauche,
        poids=10,
        mode=MODE_REPETITIONS,
        nombre_series=4,
        repetitions_par_serie=10,
        duree=0,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=souleve_roumain,
        poids=10,
        mode=MODE_REPETITIONS,
        nombre_series=4,
        repetitions_par_serie=8,
        duree=0,
        repos_entre_series=60,
        repos_apres=90
    ),
    BlocExercice(
        exercice=crunches,
        poids=0,
        mode=MODE_REPETITIONS,
        nombre_series=3,
        repetitions_par_serie=17,
        duree=0,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=planche,
        poids=0,
        mode=MODE_MAINTIEN,
        nombre_series=3,
        repetitions_par_serie=0,
        duree=40,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=planche_laterale_droite,
        poids=0,
        mode=MODE_MAINTIEN,
        nombre_series=1,
        repetitions_par_serie=0,
        duree=35,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=planche_laterale_gauche,
        poids=0,
        mode=MODE_MAINTIEN,
        nombre_series=1,
        repetitions_par_serie=0,
        duree=35,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=planche_laterale_droite,
        poids=0,
        mode=MODE_MAINTIEN,
        nombre_series=1,
        repetitions_par_serie=0,
        duree=35,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=planche_laterale_gauche,
        poids=0,
        mode=MODE_MAINTIEN,
        nombre_series=1,
        repetitions_par_serie=0,
        duree=35,
        repos_entre_series=45,
        repos_apres=90
    ),
])