from session.circuit import Circuit, BlocExercice,Exercice

from mouvements.exercices import (
    curl_biceps_droit,
    curl_biceps_gauche,
    elevation_laterale,
    pompe,
    extension_triceps_au_dessus_de_la_tete,
    developpe_couche_sol,
    developpe_epaule,
    crunches
)

Test_exercice = Circuit([
    BlocExercice(
        exercice=curl_biceps_droit,
        poids=0,
        mode="repetitions",
        nombre_series=1,
        repetitions_par_serie=1000,
        repos_entre_series=30,
        repos_apres=60
    )
])

seance_bras = Circuit([
    BlocExercice(
        exercice=curl_biceps_droit,
        poids=8,
        mode="repetitions",
        nombre_series=2,
        repetitions_par_serie=5,
        repos_entre_series=5,
        repos_apres=10
    ),
    BlocExercice(
        exercice=curl_biceps_gauche,
        poids=8,
        mode="repetitions",
        nombre_series=1,
        repetitions_par_serie=5,
        repos_entre_series=30,
        repos_apres=0
    )
])

seance_test = Circuit([
    BlocExercice(
        exercice=curl_biceps_droit,
        poids=8,
        mode="repetitions",
        nombre_series=1,
        repetitions_par_serie=5,
        repos_entre_series=5,
        repos_apres=5
    ),
    BlocExercice(
        exercice=curl_biceps_gauche,
        poids=8,
        mode="repetitions",
        nombre_series=1,
        repetitions_par_serie=5,
        repos_entre_series=5,
        repos_apres=5
    ),
    BlocExercice(
        exercice=elevation_laterale,
        poids=5,
        mode="repetitions",
        nombre_series=1,
        repetitions_par_serie=5,
        repos_entre_series=5,
        repos_apres=5
    ),
    BlocExercice(
        exercice=pompe,
        poids=0,
        mode="repetitions",
        nombre_series=1,
        repetitions_par_serie=5,
        repos_entre_series=5,
        repos_apres=5
    ),
    BlocExercice(
        exercice=extension_triceps_au_dessus_de_la_tete,
        poids=14,
        mode="repetitions",
        nombre_series=1,
        repetitions_par_serie=5,
        repos_entre_series=5,
        repos_apres=5
    ),
    BlocExercice(
        exercice=developpe_couche_sol,
        poids=10,
        mode="repetitions",
        nombre_series=1,
        repetitions_par_serie=5,
        repos_entre_series=5,
        repos_apres=0
    )
])

seance_Upper_Push = Circuit([
    BlocExercice(
        exercice=developpe_couche_sol,
        poids=10,
        mode="repetitions",
        nombre_series=4,
        repetitions_par_serie=12,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=pompe,
        poids=0,
        mode="repetitions",
        nombre_series=4,
        repetitions_par_serie=10,
        repos_entre_series=60,
        repos_apres=90
    ),
    BlocExercice(
        exercice=developpe_epaule,
        poids=8,
        mode="repetitions",
        nombre_series=3,
        repetitions_par_serie=12,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=elevation_laterale,
        poids=5,
        mode="repetitions",
        nombre_series=3,
        repetitions_par_serie=11,
        repos_entre_series=45,
        repos_apres=90
    ),
    BlocExercice(
        exercice=extension_triceps_au_dessus_de_la_tete,
        poids=14,
        mode="repetitions",
        nombre_series=3,
        repetitions_par_serie=10,
        repos_entre_series=60,
        repos_apres=0
    ),
])